Repository Material-Blazor/Material.Blazor, pull requests merged in 2020-05, with the labels that each got.

#62 Rework of radiobuttons and group
  BlazorMdc.Demo.CommonUI/Pages/RadioButtonsSample/RadioButtonsSample.razor
  BlazorMdc/Base/MdcInputComponentBase.cs
  BlazorMdc/BlazorMdc.csproj
  BlazorMdc/Components/MdcRadioButton/MdcRadioButton.razor
  BlazorMdc/Components/MdcTextArea/MdcTextArea.razor
  BlazorMdc/Components/MdcTextField/MdcTextField.razor
  BlazorMdc/Plus/PMdcNumericDoubleField/PMdcNumericDoubleField.razor
  BlazorMdc/Plus/PMdcNumericIntField/PMdcNumericIntField.razor
  BlazorMdc/Plus/PMdcRadioButtonGroup/PMdcRadioButtonGroup.razor
Labels: enhancement

#72 2020-05-06 Bug fixes and Timout as uint
  BlazorMdc/Plus/PMdcToast/Configuration/PMdcToastServiceConfiguration.cs
  BlazorMdc/Plus/PMdcToast/Configuration/PMdcToastSettings.cs
  BlazorMdc/Plus/PMdcToast/Services/IPmdcToastService.cs
  BlazorMdc/Plus/PMdcToast/Services/PMdcToastService.cs
Labels: bug

#74 2020-05-07 Bug Fixes
  BlazorMdc.Demo.CommonUI/Pages/Index/Index.razor
  BlazorMdc.Demo.CommonUI/Pages/TabBarSample/TabBarSample.razor
  BlazorMdc.Demo.CommonUI/Pages/ToastSample/ToastSample.razor
  BlazorMdc.sln
  BlazorMdc/Base/MdcInputComponentBase.cs
  BlazorMdc/Base/MdcValidatingInputComponentBase.cs
  BlazorMdc/BlazorMdc.csproj
  BlazorMdc/Components/MdcCheckbox/MdcCheckbox.razor
  BlazorMdc/Components/MdcIconButtonToggle/MdcIconButtonToggle.razor
  BlazorMdc/Components/MdcSelect/MdcSelect.razor
  BlazorMdc/Components/MdcTabBar/MdcTabBar.razor
  BlazorMdc/Plus/PMdcAnimatedNavigation/PMdcAnimatedNavigation.razor
  BlazorMdc/Plus/PMdcSlidingTabBar/PMdcSlidingTabBar.razor
  BlazorMdc/Plus/PMdcToast/Services/IPmdcToastService.cs
  BlazorMdc/Plus/PMdcToast/Services/PMdcToastService.cs
  README.md
  azure-pipelines.yml
Labels: minor version pr

#75 2020-05-07 Package number -> 0.26.0
  BlazorMdc/BlazorMdc.csproj
Labels: minor version pr

#78 2020-05-08 Two way binding
  BlazorMdc.Demo.Blazor/Program.cs
  BlazorMdc.Demo.CommonUI/Pages/ButtonSample/ButtonSample.razor
  BlazorMdc.Demo.CommonUI/Pages/DatePickerSample/DatePickerSample.razor
  BlazorMdc.Demo.CommonUI/Pages/Index/Index.razor
  BlazorMdc.Demo.CommonUI/Pages/RadioButtonsSample/RadioButtonsSample.razor
  BlazorMdc.Demo.CommonUI/Pages/SelectSample/SelectSample.razor
  BlazorMdc.Demo.CommonUI/Pages/SwitchSample/SwitchSample.razor
  BlazorMdc.Demo.CommonUI/Services/DemoConfiguration.cs
  BlazorMdc.Demo.CommonUI/Shared/MainLayout.razor
  BlazorMdc.Demo.WebServer/Pages/index_server.cshtml
  BlazorMdc.Demo.WebServer/Startup/Startup.cs
  BlazorMdc/Base/MdcInputComponentBase.cs
  BlazorMdc/Base/MdcValidatingInputComponentBase.cs
  BlazorMdc/Components/MdcCheckbox/MdcCheckbox.razor
  BlazorMdc/Components/MdcIconButtonToggle/MdcIconButtonToggle.razor
  BlazorMdc/Components/MdcRadioButton/MdcRadioButton.razor
  BlazorMdc/Components/MdcSelect/MdcSelect.razor
  BlazorMdc/Components/MdcSwitch/MdcSwitch.razor
  BlazorMdc/Components/MdcTopAppBar/MdcTopAppBar.razor
  BlazorMdc/Plus/PMdcDatePicker/InternalDatePickerPanel.razor
  BlazorMdc/Plus/PMdcDatePicker/PMdcDatePicker.razor
  BlazorMdc/Plus/PMdcPaginator/PMdcPaginator.razor
  BlazorMdc/Plus/PMdcRadioButtonGroup/PMdcRadioButtonGroup.razor
  BlazorMdc/Scripts/scripts.js
  README.md
Labels: minor version pr

#80 2020-05-10 Top App Bar bug fix and package number update
  BlazorMdc/BlazorMdc.csproj
  BlazorMdc/Components/MdcSelect/MdcSelect.razor
  BlazorMdc/Components/MdcTopAppBar/MdcTopAppBar.razor
Labels: minor version pr

#90 2020-05-14 3 line MdcList implemented
  BlazorMdc.Demo.CommonUI/Pages/ListSample/ListSample.razor
  BlazorMdc.Demo.CommonUI/Pages/PagedDataListSample/PagedDataListSample.razor
  BlazorMdc/BlazorMdc.csproj
  BlazorMdc/Components/MdcList/MdcList.razor
  BlazorMdc/Components/MdcList/MdcList.scss
  BlazorMdc/Styles/styles.scss
  README.md
Labels: minor version pr

#92 2020-05-14 Native Event Propagation
  BlazorMdc.Demo.CommonUI/Pages/ButtonSample/ButtonSample.razor
  BlazorMdc.Demo.CommonUI/Pages/CardSample/CardSample.razor
  BlazorMdc.Demo.CommonUI/Pages/DatePickerSample/DatePickerSample.razor
  BlazorMdc.Demo.CommonUI/Pages/DialogSample/DialogSample.razor
  BlazorMdc.Demo.CommonUI/Pages/MenuSample/MenuSample.razor
  BlazorMdc.Demo.CommonUI/Pages/SlidingContentSample/SlidingContentSample.razor
  BlazorMdc.Demo.CommonUI/Pages/TabBarSample/TabBarSample.razor
  BlazorMdc.Demo.CommonUI/Pages/ToastSample/ToastSample.razor
  BlazorMdc.Demo.CommonUI/Pages/WrappedInputComponentSample/WrappedInputComponentSample.razor
  BlazorMdc.Demo.CommonUI/Shared/MainLayout.razor
  BlazorMdc.Demo.WebServer/Pages/index_server.cshtml
  BlazorMdc/Base/MdcComponentBase.cs
  BlazorMdc/Base/MdcInputComponentBase.cs
  BlazorMdc/BlazorMdc.csproj
  BlazorMdc/Components/MdcButton/MdcButton.razor
  BlazorMdc/Components/MdcCard/MdcCard.razor
  BlazorMdc/Components/MdcCheckbox/MdcCheckbox.razor
  BlazorMdc/Components/MdcIconButton/MdcIconButton.razor
  BlazorMdc/Components/MdcIconButtonToggle/MdcIconButtonToggle.razor
  BlazorMdc/Components/MdcList/MdcList.scss
  BlazorMdc/Components/MdcList/MdcListItem.razor
  BlazorMdc/Components/MdcTextArea/MdcTextArea.razor
  BlazorMdc/Components/MdcTextField/MdcTextField.razor
  BlazorMdc/Components/MdcTopAppBar/MdcTopAppBar.razor
  BlazorMdc/Plus/PMdcConfirmationDialog/PMdcConfirmationDialog.razor
  BlazorMdc/Plus/PMdcDatePicker/InternalDatePickerDayButton.razor
  BlazorMdc/Plus/PMdcDatePicker/InternalDatePickerYearButton.razor
  BlazorMdc/Plus/PMdcDatePicker/PMdcDatePicker.scss
  BlazorMdc/Plus/PMdcDebouncedTextField/PMdcDebouncedTextField.razor
  BlazorMdc/Plus/PMdcNumericDoubleField/PMdcNumericDoubleField.razor
  BlazorMdc/Plus/PMdcPaginator/PMdcPaginator.razor
  BlazorMdc/Plus/PMdcToast/PMdcToastAnchor.razor
  README.md
Labels: minor version pr
